function outputs = writePaperReports(projectRoot, reportsDir, runMode)
%writePaperReports Create paper update and replacement-status reports.

dpimnumeric.ensureDir(reportsDir);

if nargin < 3 || strlength(string(runMode)) == 0
    runMode = "small";
end

runMode = lower(string(runMode));
switch runMode
    case "full"
        wrapperDescription = "full rebuild wrapper";
        tableStatus = "full_run_completed_review_required";
        tableReason = "Full rerun completed; review numerical credibility before manuscript replacement.";
        finiteStatus = "full_run_completed_review_required";
        nonlinearStatus = "full_run_completed_lockedmean_review_required";
        e6Status = "full_run_completed_gf_surrogate";
        plateStatus = "full_run_completed_existing_sigma1_pool";
        plateReason = "Full coverage rerun completed over the existing dual-plate sigma=1 pool; this is not a rebuilt sigma=dy pool.";
        riskFirstLine = "- Full mode has been executed, but manuscript replacement still requires targeted numerical review.";
    case "medium"
        wrapperDescription = "medium rebuild wrapper";
        tableStatus = "medium_ready_not_full";
        tableReason = "Medium rerun completed; still not a final paper-scale table.";
        finiteStatus = "medium_ready_not_full";
        nonlinearStatus = "medium_ready_not_full";
        e6Status = "medium_interface_not_full";
        plateStatus = "medium_existing_sigma1_pool";
        plateReason = "Medium rerun uses the existing dual-plate sigma=1 pool and is not a rebuilt sigma=dy pool.";
        riskFirstLine = "- No full-scale experiments are run by this wrapper.";
    otherwise
        wrapperDescription = "small rebuild wrapper";
        tableStatus = "small_ready_not_full";
        tableReason = "Small reproducibility table; not a final paper-scale table.";
        finiteStatus = "small_ready_not_full";
        nonlinearStatus = "small_ready_not_full";
        e6Status = "small_ready_not_full";
        plateStatus = "small_ready_not_full";
        plateReason = "Uses finite grid small interface.";
        riskFirstLine = "- No full-scale experiments are run by this wrapper.";
end

paperUpdatePlan = [
    "# Paper Update Plan"
    ""
    "This file is generated by the " + wrapperDescription + "."
    ""
    "## Use Rules"
    ""
    "- Use `reports/model_lock.json` as the nonlinear model definition."
    "- Use `results/E*/config.json` and `results/E*/metadata.json` to trace figures and tables."
    "- Treat small-run numerical outputs as reproducibility checks and interface validation, not full paper-scale conclusions."
    "- Replace manuscript placeholder figures only after rerunning medium/full configurations and checking the figure replacement table."
    ""
    "## Immediate Manuscript Actions"
    ""
    "1. Replace or mark all existing placeholder figures in the latest paper draft."
    "2. Use E1 finite-B outputs for the finite bootstrap grid baseline."
    "3. Use E4/E5 only after checking that the locked model `z=mean(theta)` is the intended final formula."
    "4. Keep E6--E8 marked as interface-ready until full data and compute budgets are approved."
    ""
];
dpimnumeric.writeText(fullfile(reportsDir, "paper_update_plan.md"), strjoin(paperUpdatePlan, newline) + newline);

figureTable = table( ...
    ["DPIM_CI_topjournal_revised_v5_no_wrong_formula.pdf"; ...
     "DPIM_CI_topjournal_revised_v5_no_wrong_formula.pdf"; ...
     "DPIM_CI_topjournal_revised_v5_no_wrong_formula.pdf"; ...
     "DPIM_CI_topjournal_revised_v5_no_wrong_formula.pdf"; ...
     "DPIM_CI_topjournal_revised_v5_no_wrong_formula.pdf"], ...
    ["finite-B calibration"; "R-order coverage"; "nonlinear tail"; "bootstrap-t diagnostics"; "plate/simultaneous band"], ...
    ["fig:finiteB"; "fig:Rorder"; "fig:nonlinear-tail"; "fig:small-denominator"; "fig:plate-band"], ...
    ["placeholder"; "placeholder"; "placeholder"; "placeholder"; "placeholder"], ...
    ["results/E1_finite_B/figures/finite_B_grid_error.png"; ...
     "results/E2_R_order/figures/R_order_coverage_error.png"; ...
     "results/E4_nonlinear_tail/figures/nonlinear_tail_density.png"; ...
     "results/E5_bootstrap_t_instability/figures/bootstrap_t_diagnostics.png"; ...
     "results/E8_simultaneous_band/figures/simultaneous_band_coverage.png"], ...
    [finiteStatus; finiteStatus; nonlinearStatus; nonlinearStatus; plateStatus], ...
    ["Generated by " + wrapperDescription + "; rerun at paper scale before final citation if this is not full mode."; ...
     "Generated by " + wrapperDescription + "; slope is diagnostic only."; ...
     "Uses locked model with z=mean(theta); review manuscript fit before citation."; ...
     "Uses locked model with z=mean(theta); review manuscript fit before citation."; ...
     plateReason], ...
    'VariableNames', {'paper_file', 'section', 'figure_label', 'old_figure_name', ...
    'new_figure_path', 'status', 'reason'});
writetable(figureTable, fullfile(reportsDir, "figure_replacement_table.csv"));

tableReplacement = table( ...
    ["finite-B calibration"; "R-order coverage"; "linear beam"; "nonlinear tail"; "bootstrap-t diagnostics"; "weights/RQMC"; "plate"; "simultaneous band"], ...
    ["results/E1_finite_B/summary.csv"; "results/E2_R_order/summary.csv"; ...
     "results/E3_linear_beam_n_h/summary.csv"; "results/E4_nonlinear_tail/summary.csv"; ...
     "results/E5_bootstrap_t_instability/summary.csv"; "results/E6_weights_GF_RQMC/summary.csv"; ...
     "results/E7_plate_SFEM/summary.csv"; "results/E8_simultaneous_band/summary.csv"], ...
    [repmat(tableStatus, 5, 1); e6Status; plateStatus; plateStatus], ...
    [repmat(tableReason, 5, 1); ...
     "GF row remains a surrogate interface unless the project-specific GF optimizer is wired in."; ...
     plateReason; ...
     plateReason], ...
    'VariableNames', {'section', 'new_table_path', 'status', 'reason'});
writetable(tableReplacement, fullfile(reportsDir, "table_replacement_table.csv"));

conclusionDraft = [
    "% Numerical conclusion draft generated from the rebuild wrapper."
    "% Review before pasting into the manuscript."
    "\paragraph{Rebuild status.}"
    "The generated configuration establishes executable interfaces for E1--E8 and reproducible output bundles with configuration and metadata files."
    "Finite-bootstrap grid calibration can be checked directly through the exact integer rule \(C_{0,B}=(k_+-k_-)/(B+1)\)."
    "All nonlinear rebuild calculations use \(g(\theta)=z+0.4z^3+0.8ze\), \(z=d^{-1}\sum_i\theta_i\), and \(e=d^{-1}\sum_i\theta_i^2-1\)."
    "The rebuild outputs should be separated into directly rerun evidence and remaining surrogate or reused-pool components."
    ""
];
dpimnumeric.writeText(fullfile(reportsDir, "numerical_conclusion_draft.tex"), strjoin(conclusionDraft, newline) + newline);

risks = [
    "# Remaining Risks"
    ""
    riskFirstLine
    "- Existing nonlinear scripts may contain older `z=a'*theta` conventions; new wrapper outputs use `z=mean(theta)`."
    "- E6 uses a small GF-weight interface surrogate unless a project-specific GF optimizer is explicitly wired in."
    "- E7/E8 rely on existing dual-plate reference and RQMC sample files when present."
    "- The currently reused dual-plate pool was generated with `sigma=1`, while the thesis text states `sigma=dy`; this wrapper does not rebuild that pool."
    "- Figure replacement remains gated on targeted review even after a full rerun."
    "- The current folder is not a Git repository; metadata records wrapper file hashes instead of a commit id."
    ""
    "Project root:"
    string(projectRoot)
    ""
];
dpimnumeric.writeText(fullfile(reportsDir, "remaining_risks.md"), strjoin(risks, newline) + newline);

outputs = struct();
outputs.paper_update_plan = fullfile(reportsDir, "paper_update_plan.md");
outputs.figure_replacement_table = fullfile(reportsDir, "figure_replacement_table.csv");
outputs.table_replacement_table = fullfile(reportsDir, "table_replacement_table.csv");
outputs.numerical_conclusion_draft = fullfile(reportsDir, "numerical_conclusion_draft.tex");
outputs.remaining_risks = fullfile(reportsDir, "remaining_risks.md");
end
