function outputPath = writeModelLock(reportsDir, runMode)
%writeModelLock Write the locked nonlinear-model specification.

if nargin < 2 || strlength(string(runMode)) == 0
    runMode = "small";
end

modelLock = struct();
modelLock.nonlinear_model = struct( ...
    "formula", "g(theta,t)=b+c_t*t+z+alpha*z^3+beta*z*e", ...
    "z", "mean(theta)", ...
    "e", "mean(theta.^2)-1", ...
    "default_b", 0, ...
    "default_c_t", 0, ...
    "default_alpha", 0.40, ...
    "default_beta", 0.80, ...
    "static_formula", "g(theta)=z+0.4*z^3+0.8*z*e", ...
    "implementation_note", "The new wrapper computes z as mean(theta,2), matching the prompt lock.");
modelLock.ci_methods = ["t", "percentile", "bootstrap_t", "hybrid"];
modelLock.required_outputs = ["coverage", "interval_length", "left_miss", "right_miss", ...
    "A_lambda", "effective_weights", "metadata"];
modelLock.run_modes = ["small", "medium", "full"];
modelLock.current_wrapper_mode = lower(string(runMode));
modelLock.non_git_metadata_policy = "If no Git repository is present, metadata records MD5 file hashes for wrapper files.";

outputPath = fullfile(reportsDir, "model_lock.json");
dpimnumeric.writeJson(outputPath, modelLock);
end
