function problems = dpim_weighted_define_problems(runMode)
%DPIM_WEIGHTED_DEFINE_PROBLEMS Define input distributions and responses.
% U-points are transformed into target probability space before response
% evaluation.  The Voronoi weights are also computed in the same target
% probability space.
if nargin < 1; runMode = "small"; end

problems = struct('name',{}, 'short_name',{}, 'd',{}, 'target_distribution',{}, ...
    'center_transform',{}, 'provider',{}, 'lognormal_mu',{}, 'lognormal_sigma',{}, ...
    'response_fun',{}, 'y_grid',{}, 'y_points',{}, 'failure_thresholds',{}, 'L_phys',{});

% E3: smooth normal-response model.
problems(end+1) = struct( ...
    'name', 'E3_beam_smooth', ...
    'short_name', 'E3', ...
    'd', 3, ...
    'target_distribution', 'standard_normal', ...
    'center_transform', 'normal_icdf', ...
    'provider', 'voronoi_ci_probability_weights_provider', ...
    'lognormal_mu', 0.0, ...
    'lognormal_sigma', 1.0, ...
    'response_fun', @(theta) 0.5 + 0.25*theta(:,1) + 0.10*theta(:,2) + 0.05*theta(:,3), ...
    'y_grid', linspace(-0.8, 1.8, 500)', ...
    'y_points', [0.5, 1.1], ...
    'failure_thresholds', [0.95, 1.10], ...
    'L_phys', 0.6);

% E4: nonlinear multimodal-ish normal model.
problems(end+1) = struct( ...
    'name', 'E4_nonlinear_multimodal', ...
    'short_name', 'E4', ...
    'd', 10, ...
    'target_distribution', 'standard_normal', ...
    'center_transform', 'normal_icdf', ...
    'provider', 'voronoi_ci_probability_weights_provider', ...
    'lognormal_mu', 0.0, ...
    'lognormal_sigma', 1.0, ...
    'response_fun', @(theta) 1.0 + 0.75*tanh(0.45*sum(theta,2)./sqrt(size(theta,2))) + 0.16*(theta(:,1).^2-1) + 0.10*sin(theta(:,2).*theta(:,3)), ...
    'y_grid', linspace(-0.8, 2.8, 600)', ...
    'y_points', [1.0, 1.85], ...
    'failure_thresholds', [1.75, 2.10], ...
    'L_phys', 1.2);

% E5: lognormal right-tail model.  This intentionally uses the lognormal
% Voronoi-weight provider rather than treating transformed samples as
% equal-weight response samples.
problems(end+1) = struct( ...
    'name', 'E5_lognormal_right_tail', ...
    'short_name', 'E5', ...
    'd', 5, ...
    'target_distribution', 'lognormal', ...
    'center_transform', 'lognormal_icdf', ...
    'provider', 'voronoi_ci_probability_weights_provider_lognormal', ...
    'lognormal_mu', 0.0, ...
    'lognormal_sigma', 0.45, ...
    'response_fun', @(theta) 2.0 + 0.14*sum(theta,2) + 0.35*theta(:,1).*theta(:,2)./(1.0+theta(:,3)), ...
    'y_grid', linspace(2.0, 5.5, 600)', ...
    'y_points', [2.8, 4.2], ...
    'failure_thresholds', [4.0, 4.7], ...
    'L_phys', 0.8);

if lower(string(runMode)) == "full"
    % E6: stronger nonlinear lognormal response.
    problems(end+1) = struct( ...
        'name', 'E6_lognormal_nonlinear', ...
        'short_name', 'E6', ...
        'd', 8, ...
        'target_distribution', 'lognormal', ...
        'center_transform', 'lognormal_icdf', ...
        'provider', 'voronoi_ci_probability_weights_provider_lognormal_nonlinear', ...
        'lognormal_mu', 0.0, ...
        'lognormal_sigma', 0.40, ...
        'response_fun', @(theta) 1.5 + 0.10*sum(theta,2) + 0.30*log(1+theta(:,1).*theta(:,2)) + 0.08*(theta(:,3)-1).^2, ...
        'y_grid', linspace(1.5, 5.0, 600)', ...
        'y_points', [2.5, 3.6], ...
        'failure_thresholds', [3.5, 4.2], ...
        'L_phys', 0.9);
end
end
