function [U, pointInfo] = dpim_generate_point_set(n, d, methodName, seed)
%DPIM_GENERATE_POINT_SET Generate integration points in [0,1]^d.
%
% Syntax:
%   U = dpim_generate_point_set(n, d, methodName, seed)
%   [U, pointInfo] = dpim_generate_point_set(n, d, methodName, seed)
%
% Methods:
%   "mc"              : pseudorandom Monte Carlo points.
%   "sobol_qmc"       : deterministic Sobol points from sobolset.
%   "sobol_scrambled" : Owen/MatousekAffineOwen-scrambled Sobol points.
%   "halton_shifted"  : randomly shifted Halton points.
%
% Important implementation note:
%   Sobol scrambling is invoked directly through sobolset + scramble inside
%   try/catch.  In MATLAB R2026 with Statistics and Machine Learning Toolbox
%   installed, methodName="sobol_scrambled" should normally return
%   pointInfo.actual_method="sobol_scrambled".

if nargin < 4 || isempty(seed)
    seed = 1;
end

n = round(double(n));
d = round(double(d));
seed = round(double(seed));
methodName = lower(char(string(methodName)));

if n <= 0 || d <= 0
    error('n and d must be positive integers.');
end

pointInfo = struct();
pointInfo.requested_method = string(methodName);
pointInfo.actual_method = string(methodName);
pointInfo.seed = seed;
pointInfo.n = n;
pointInfo.d = d;
pointInfo.fallback_used = false;
pointInfo.message = "";

switch methodName
    case {'mc', 'random'}
        oldState = rng;
        rng(seed, 'twister');
        cleanupObj = onCleanup(@() rng(oldState)); %#ok<NASGU>
        U = rand(n, d);
        pointInfo.actual_method = "mc";
        pointInfo.message = "Pseudorandom Monte Carlo points.";

    case {'sobol_qmc', 'sobol', 'qmc'}
        [ok, U, msg] = local_try_sobol(n, d, false, seed);
        if ok
            pointInfo.actual_method = "sobol_qmc";
            pointInfo.message = "Deterministic Sobol points generated by sobolset.";
        else
            warning('sobol_qmc failed: %s. Using deterministic Halton fallback.', msg);
            U = local_halton_points(n, d, 64);
            pointInfo.actual_method = "halton_fallback";
            pointInfo.fallback_used = true;
            pointInfo.message = "Sobol QMC failed; deterministic Halton fallback used. Original error: " + string(msg);
        end

    case {'sobol_scrambled', 'scrambled_sobol', 'rqmc'}
        [ok, U, msg] = local_try_sobol(n, d, true, seed);
        if ok
            pointInfo.actual_method = "sobol_scrambled";
            pointInfo.message = "Scrambled Sobol points generated by sobolset + scramble(''MatousekAffineOwen'').";
        else
            warning('scrambled Sobol failed: %s. Using randomly shifted Halton fallback.', msg);
            base = local_halton_points(n, d, 64);
            oldState = rng;
            rng(seed, 'twister');
            cleanupObj = onCleanup(@() rng(oldState)); %#ok<NASGU>
            shift = rand(1, d);
            U = mod(base + shift, 1);
            pointInfo.actual_method = "halton_shifted_fallback";
            pointInfo.fallback_used = true;
            pointInfo.message = "Scrambled Sobol failed; randomly shifted Halton fallback used. Original error: " + string(msg);
        end

    case {'halton', 'halton_shifted'}
        base = local_halton_points(n, d, 64);
        oldState = rng;
        rng(seed, 'twister');
        cleanupObj = onCleanup(@() rng(oldState)); %#ok<NASGU>
        shift = rand(1, d);
        U = mod(base + shift, 1);
        pointInfo.actual_method = "halton_shifted";
        pointInfo.message = "Randomly shifted Halton points.";

    otherwise
        error('Unsupported point method: %s', methodName);
end

% Protect inverse-CDF transforms against exact 0 or 1.
epsProb = 1e-15;
U = min(max(U, epsProb), 1 - epsProb);
end

function [ok, U, msg] = local_try_sobol(n, d, doScramble, seed)
ok = false;
U = [];
msg = '';
try
    p = sobolset(d, 'Skip', 64, 'Leap', 0);
    if doScramble
        oldState = rng;
        rng(seed, 'twister');
        cleanupObj = onCleanup(@() rng(oldState)); %#ok<NASGU>
        p = scramble(p, 'MatousekAffineOwen');
    end
    U = net(p, n);
    ok = true;
catch ME
    msg = ME.message;
end
end

function U = local_halton_points(n, d, skip)
%LOCAL_HALTON_POINTS Small pure-MATLAB Halton generator.
if nargin < 3
    skip = 0;
end
pr = local_first_primes(d);
U = zeros(n, d);
idx = (1:n).' + skip;
for j = 1:d
    U(:, j) = local_radical_inverse(idx, pr(j));
end
end

function x = local_radical_inverse(k, base)
k = double(k(:));
x = zeros(size(k));
f = 1 / base;
while any(k > 0)
    digit = mod(k, base);
    x = x + f * digit;
    k = floor(k / base);
    f = f / base;
end
end

function p = local_first_primes(d)
p = zeros(1, d);
count = 0;
candidate = 2;
while count < d
    if local_is_prime(candidate)
        count = count + 1;
        p(count) = candidate;
    end
    candidate = candidate + 1;
end
end

function tf = local_is_prime(x)
if x < 2
    tf = false;
    return;
end
if x == 2
    tf = true;
    return;
end
if mod(x, 2) == 0
    tf = false;
    return;
end
r = floor(sqrt(x));
tf = true;
for q = 3:2:r
    if mod(x, q) == 0
        tf = false;
        return;
    end
end
end
